### PR TITLE
Add a proper autotools build system

### PR DESCRIPTION
**Pull request by ikeydoherty**
Note this will change how you handle translations. To update the pot file, simply:

```bash

cd po
rm alternative-toolbar.pot
make alternative-toolbar.pot
```

Also note this will streamline your release process, as you'll simply need to edit the version in `configure.ac`, and tag the release. You can now do a `make distcheck` to produce a sane, versioned .tar.xz for release and use within distributions.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Note that I renamed the `.ui` files to `.glade` so that intltool will automatically handle the generation, extraction, etc.

**Comment by fossfreedom** [comment]
wow - this looks great.  Many thanks.

Quick question - I'm assuming the README needs to have something like the following?

"install the intltool package for your distro.

Then run:
 ./autogen.sh --prefix=/usr
make
sudo make install
"

When I do the above I dont see any languages from the po folder being installed in /usr/share/locale/

Am I missing something from the autogen.sh command line?

**Comment by fossfreedom** [comment]
ok - slightly modified Makefile.am

<pre>
diff --git a/Makefile.am b/Makefile.am
index 12e75b1..cf2ebf2 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -5,6 +5,7 @@
 
 rb_plugin_libdir = $(libdir)/rhythmbox/plugins/alternative-toolbar
 
+SUBDIRS = po
 
 CLEANFILES = \
        alternative-toolbar.plugin \
@@ -12,7 +13,8 @@ CLEANFILES = \
        ./po/Makefile \
        ./po/POTFILES \
        ./po/Makefile.in \
-       ./po/stamp-it
+       ./po/stamp-it \
+       ./po/*.gmo
 
 DISTCLEANFILES = \
        alternative-toolbar.plugin \
@@ -20,7 +22,8 @@ DISTCLEANFILES = \
        ./po/Makefile \
        ./po/POTFILES \
        ./po/Makefile.in \
-       ./po/stamp-it
+       ./po/stamp-it \
+       ./po/*.gmo
 
 PLUGIN_FILES = \
        alttoolbar_type.py \
</pre>

that compiles and installs the languages in the po subfolder.

What I can't fathom is why when I run a 'make clean',  po/alternative-toolbar.pot also gets deleted

**Comment by fossfreedom** [comment]
ok - have now merged.

Thanks for all of this.

**Comment by ikeydoherty** [comment]
Ah good catch, cheers :)

**Comment by fossfreedom** [comment]
@ikeydoherty - just to say - I presume you were going to look at adding this to the Solus Linux repository at some point?

If you were - just shout - I'm happy to test this out for you to ensure all things work as expected.

BTW - I note you've released v1.0 of Solus Linux - congrats - looks like from the stuff I've read you've got very positive reviews.  Well done :)

**Pull request merged**
