### PR TITLE
Fix broken Ctrl-f shortcut to search

### LINKED ISSUE #98: Ctrl-F only focuses on the search field if it's already visible
If you click on the magnifying glass button, the search bar pops down, and then Ctrl-F focuses on the search field, like it should.

But if you hit Ctrl-F before exposing the search bar, it either does nothing or opens a tiny little search field somewhere else.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40062725-ctrl-f-only-focuses-on-the-search-field-if-it-s-already-visible?utm_campaign=plugin&utm_content=tracker%2F10046800&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F10046800&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by McSinyx**
This fixes #98. However, there are a few remaining problems:

* Ctrl-f fail to focus search entry for SoundCloud on non-CSD mode
* One cannot Tab to select search result (this is quite of a separate issue though)

### CODE REVIEW

**Comment by fossfreedom** [comment]
thanks for this.  I'm a little tied up with 18.10 Ubuntu Budgie matters at the moment - but will definitely come back to this as soon as the release settles down.  Cheers again.

**Comment by McSinyx** [comment]
Aww, the Moka icons give me nostalgia, are they still actively developed? Also great default application choice on Ubuntu Budgie. This will be on my list of distros to recommend to new-comers (personally I'd prefer semi-rolling like Debian testing tho since Ubuntu has long reputation of making major changes every release and thus normal `apt-get dist-upgrade` cannot promise to work).

**Comment by fossfreedom** [comment]
Sound Cloud focus appears to be working for me.

The toggle action when clicking on the headerbar search button is no longer working though.

We'll need to figure out what's broken there.

The search first visible animation is also now no longer there - admittedly it didnt subsequently work on a toggle.  Will need to play around in this area to tidy up.

However the key part for the keyboard toggle now works - so thanks for that.  Good basis to work from.

**Comment by fossfreedom** [comment]
Should now be resolved - now use the keybinder python module to detect CTRL+F

**Comment by fossfreedom** [comment]
ok - will relook at this again - see if I can remove the keybinder dependency .  cheers. Don't worry about the conflict. I'll deal.

**Pull request closed without merging**
